#!/bin/bash

my_pid=$$
echo "My process ID is $my_pid"

echo "Launching gazebo_nav.launch"
roslaunch hyperlync_robot hyperlync_simulator.launch &
sleep 6s
pid="$pid $!"


echo "rviz"
rosrun rviz rviz -d `rospack find hyperlync_robot`/andbot.rviz &


trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

